import os

import pytest

from extensions import db
import routes.threat_intel as threat_intel
from extensions import db
from models import ROLE_ANALYST, ROLE_THREAT_INTEL, Asset, AuditLog, AuthorizedTarget, ReportShare, User, Vulnerability
from services import epss_service, report_service, report_share_service, target_service
from tests.conftest import login


@pytest.fixture(autouse=True)
def _no_network(monkeypatch):
    epss_service.clear_cache()
    monkeypatch.setattr(threat_intel, "recent_kev_entries", lambda limit=10: [])
    monkeypatch.setattr(epss_service, "_fetch_json", lambda url: {"status": "OK", "data": []})
    yield
    epss_service.clear_cache()


def _user(username, role, first="", last=""):
    user = User(username=username, email=f"{username}@example.com", role=role, first_name=first or None, last_name=last or None)
    user.set_password("SharePass#123")
    db.session.add(user)
    db.session.commit()
    return user


@pytest.fixture
def intel(app):
    return _user("intel", ROLE_THREAT_INTEL, "Ines", "Intel")


@pytest.fixture
def other_analyst(app):
    return _user("other", ROLE_ANALYST)


@pytest.fixture
def report(app, analyst_user, tmp_path):
    """A real exported CSV report on disk, generated by the analyst."""
    target = target_service.create_target(owner_id=analyst_user.id, domain="share.example.com", authorized=True)
    asset = Asset(target_id=target.id, subdomain="www.share.example.com")
    db.session.add(asset)
    db.session.commit()
    db.session.add(Vulnerability(asset_id=asset.id, severity="high", title="Exposed admin panel", description="x"))
    db.session.commit()
    return report_service.generate_csv_report(target, str(tmp_path), analyst_user.id)


def _share(client, report, note="", target_id=""):
    return client.post(f"/workspace/reports/{report.id}/share", data={"note": note, "target_id": target_id}, follow_redirects=True)


_PASSWORDS = {"analyst": "AnalystPass123!", "admin": "AdminPass123!"}   # everyone made by _user() shares one password


def _as(client, username):
    client.post("/api/auth/logout")
    assert login(client, username, _PASSWORDS.get(username, "SharePass#123")).status_code == 200


def _flashes(resp):
    return resp.get_data(as_text=True)


# ============================================================ the analyst shares
def test_an_analyst_can_share_a_report_they_exported(client, analyst_user, report):
    login(client, "analyst", "AnalystPass123!")

    resp = _share(client, report, note="Please review the admin panel exposure.")

    assert "Shared with Threat Intelligence" in _flashes(resp)
    share = ReportShare.query.one()
    assert (share.report_id, share.shared_by, share.note) == (report.id, analyst_user.id, "Please review the admin panel exposure.")
    assert share.shared_at is not None
    assert ("report_shared", f"report_id={report.id} share_id={share.id}") in [(a.action, a.detail) for a in AuditLog.query.all()]


def test_the_findings_page_offers_to_share_and_then_shows_it_is_shared(client, analyst_user, report):
    login(client, "analyst", "AnalystPass123!")
    before = client.get("/workspace/findings").get_data(as_text=True)
    assert f'action="/workspace/reports/{report.id}/share"' in before and "Threat Intelligence</th>" in before
    assert "Withdraw" not in before

    after = _flashes(_share(client, report, "see attached"))
    assert ">Shared<" in after and "Not downloaded yet" in after and "Note: see attached" in after
    assert f'action="/workspace/reports/{report.id}/unshare"' in after and f"/workspace/reports/{report.id}/share" not in after


def test_a_report_is_only_shared_once(client, analyst_user, report):
    login(client, "analyst", "AnalystPass123!")
    _share(client, report, "first")

    again = _share(client, report, "second try")

    assert "already shared" in _flashes(again)
    share = ReportShare.query.one()
    assert share.note == "first"                                                                     # the original share is untouched


def test_sharing_twice_through_the_service_returns_the_same_share(app, analyst_user, report):
    first, created = report_share_service.share_report(report, analyst_user.id, "a")
    second, created_again = report_share_service.share_report(report, analyst_user.id, "b")
    assert (created, created_again) == (True, False) and first.id == second.id and ReportShare.query.count() == 1


def test_a_long_note_is_cut_and_a_blank_one_is_dropped(app, analyst_user, report, tmp_path):
    share, _ = report_share_service.share_report(report, analyst_user.id, "x" * 900)
    assert len(share.note) == report_share_service.NOTE_MAX_LENGTH

    another = report_service.generate_csv_report(db.session.get(AuthorizedTarget, report.target_id), str(tmp_path), analyst_user.id)
    blank, _ = report_share_service.share_report(another, analyst_user.id, "   ")
    assert blank.note is None


def test_a_report_whose_file_is_gone_cannot_be_shared(client, analyst_user, report):
    os.remove(report.file_path)
    login(client, "analyst", "AnalystPass123!")

    resp = _share(client, report)

    assert "no longer available" in _flashes(resp) and ReportShare.query.count() == 0


def test_nobody_can_share_someone_elses_report(client, analyst_user, other_analyst, report):
    _as(client, "other")

    resp = _share(client, report)

    assert "Report not found" in _flashes(resp) and ReportShare.query.count() == 0


def test_an_unknown_report_cannot_be_shared(client, analyst_user):
    login(client, "analyst", "AnalystPass123!")
    resp = client.post("/workspace/reports/9999/share", data={}, follow_redirects=True)
    assert "Report not found" in _flashes(resp) and ReportShare.query.count() == 0


def test_threat_intel_and_anonymous_users_cannot_share(client, analyst_user, intel, report):
    assert "login" in client.post(f"/workspace/reports/{report.id}/share").headers["Location"]

    _as(client, "intel")
    client.post(f"/workspace/reports/{report.id}/share", data={"note": "x"})

    assert ReportShare.query.count() == 0


def test_an_admin_may_share_any_report(client, analyst_user, admin_user, report):
    login(client, "admin", "AdminPass123!")
    client.post(f"/workspace/reports/{report.id}/share", data={})
    assert ReportShare.query.one().shared_by == admin_user.id


# ============================================================ withdrawing
def test_the_owner_can_withdraw_a_shared_report(client, analyst_user, intel, report):
    login(client, "analyst", "AnalystPass123!")
    _share(client, report)

    resp = client.post(f"/workspace/reports/{report.id}/unshare", data={}, follow_redirects=True)

    assert "Withdrawn" in _flashes(resp) and ReportShare.query.count() == 0
    assert report_share_service.inbox() == []
    assert "report_share_withdrawn" in [a.action for a in AuditLog.query.all()]


def test_withdrawing_a_report_that_was_not_shared_says_so(client, analyst_user, report):
    login(client, "analyst", "AnalystPass123!")
    resp = client.post(f"/workspace/reports/{report.id}/unshare", data={}, follow_redirects=True)
    assert "was not shared" in _flashes(resp)


def test_nobody_else_can_withdraw_your_share(client, analyst_user, other_analyst, report):
    report_share_service.share_report(report, analyst_user.id)
    _as(client, "other")

    client.post(f"/workspace/reports/{report.id}/unshare", data={})

    assert ReportShare.query.count() == 1


# ============================================================ threat intelligence receives it
def test_threat_intel_sees_the_shared_report_with_who_when_and_why(client, analyst_user, intel, report):
    analyst_user.first_name, analyst_user.last_name = "Ana", "Analyst"
    db.session.commit()
    report_share_service.share_report(report, analyst_user.id, "Admin panel is internet-facing.")
    _as(client, "intel")

    html = client.get("/workspace/threat-intel").get_data(as_text=True)

    assert 'id="shared-reports"' in html and "Reports shared by analysts" in html and "1 new" in html
    assert "share.example.com" in html and "CSV" in html and "Ana Analyst" in html and "Admin panel is internet-facing." in html
    assert ">New<" in html and f"/workspace/threat-intel/reports/{ReportShare.query.one().id}/download" in html


def test_the_shared_file_is_byte_for_byte_the_one_the_analyst_exported(client, analyst_user, intel, report):
    share, _ = report_share_service.share_report(report, analyst_user.id)
    _as(client, "intel")

    resp = client.get(f"/workspace/threat-intel/reports/{share.id}/download")

    assert resp.status_code == 200
    with open(report.file_path, "rb") as fh:
        assert resp.data == fh.read()
    assert os.path.basename(report.file_path) in resp.headers["Content-Disposition"] and "attachment" in resp.headers["Content-Disposition"]
    assert ("shared_report_downloaded", f"share_id={share.id}") in [(a.action, a.detail) for a in AuditLog.query.all()]


def test_a_shared_pdf_arrives_as_a_pdf(client, analyst_user, intel, report, tmp_path):
    pdf = report_service.generate_pdf_report(db.session.get(AuthorizedTarget, report.target_id), str(tmp_path), analyst_user.id)
    share, _ = report_share_service.share_report(pdf, analyst_user.id)
    _as(client, "intel")

    resp = client.get(f"/workspace/threat-intel/reports/{share.id}/download")

    assert resp.data.startswith(b"%PDF-")


def test_a_downloaded_report_stops_being_new_for_that_analyst_only(client, analyst_user, intel, report):
    second = _user("intel2", ROLE_THREAT_INTEL)
    share, _ = report_share_service.share_report(report, analyst_user.id)
    _as(client, "intel")
    client.get(f"/workspace/threat-intel/reports/{share.id}/download")

    mine = client.get("/workspace/threat-intel").get_data(as_text=True)
    assert ">Downloaded<" in mine and "1 new" not in mine and "1 total</span>" in mine

    _as(client, "intel2")
    theirs = client.get("/workspace/threat-intel").get_data(as_text=True)
    assert "1 new" in theirs and ">New<" in theirs
    assert second.id != intel.id


def test_the_analyst_sees_when_threat_intel_has_downloaded_the_report(client, analyst_user, intel, report):
    share, _ = report_share_service.share_report(report, analyst_user.id)
    login(client, "analyst", "AnalystPass123!")
    assert "Not downloaded yet" in client.get("/workspace/findings").get_data(as_text=True)

    _as(client, "intel")
    client.get(f"/workspace/threat-intel/reports/{share.id}/download")
    _as(client, "analyst")

    page = client.get("/workspace/findings").get_data(as_text=True)
    assert ">Downloaded<" in page and "Not downloaded yet" not in page


def test_every_threat_intel_analyst_receives_the_same_report(client, analyst_user, intel, report):
    _user("intel2", ROLE_THREAT_INTEL)
    report_share_service.share_report(report, analyst_user.id)
    for name in ("intel", "intel2"):
        _as(client, name)
        assert "share.example.com" in client.get("/workspace/threat-intel").get_data(as_text=True)


def test_a_withdrawn_report_disappears_from_the_inbox_and_cannot_be_downloaded(client, analyst_user, intel, report):
    share, _ = report_share_service.share_report(report, analyst_user.id)
    report_share_service.withdraw_share(report.id, analyst_user.id)
    _as(client, "intel")

    assert "No reports have been shared with you yet." in client.get("/workspace/threat-intel").get_data(as_text=True)
    resp = client.get(f"/workspace/threat-intel/reports/{share.id}/download", follow_redirects=True)
    assert "no longer available" in _flashes(resp)


def test_a_missing_file_is_flagged_and_not_downloadable(client, analyst_user, intel, report):
    share, _ = report_share_service.share_report(report, analyst_user.id)
    os.remove(report.file_path)
    _as(client, "intel")

    assert "File unavailable" in client.get("/workspace/threat-intel").get_data(as_text=True)
    resp = client.get(f"/workspace/threat-intel/reports/{share.id}/download", follow_redirects=True)
    assert "no longer available" in _flashes(resp)
    assert "shared_report_downloaded" not in [a.action for a in AuditLog.query.all()]


def test_an_unknown_share_cannot_be_downloaded(client, intel):
    _as(client, "intel")
    resp = client.get("/workspace/threat-intel/reports/4242/download", follow_redirects=True)
    assert resp.status_code == 200 and "no longer available" in _flashes(resp)


def test_only_threat_intel_and_admins_can_download_shared_reports(client, analyst_user, admin_user, report):
    share, _ = report_share_service.share_report(report, analyst_user.id)
    url = f"/workspace/threat-intel/reports/{share.id}/download"

    assert "login" in client.get(url).headers["Location"]                                            # anonymous

    login(client, "analyst", "AnalystPass123!")
    sent_away = client.get(url)                                                                      # an analyst is sent back to their own dashboard
    assert sent_away.status_code == 302 and "/dashboard" in sent_away.headers["Location"]
    assert "shared_report_downloaded" not in [a.action for a in AuditLog.query.all()]

    _as(client, "admin")
    assert client.get(url).status_code == 200                                                         # an admin may review it


def test_a_report_that_is_not_shared_cannot_be_reached_through_threat_intel(client, analyst_user, intel, report):
    _as(client, "intel")
    # the report id is not a share id: only an actual share opens the file
    resp = client.get(f"/workspace/threat-intel/reports/{report.id}/download", follow_redirects=True)
    assert "no longer available" in _flashes(resp)


def test_a_note_cannot_inject_markup_into_the_inbox(client, analyst_user, intel, report):
    report_share_service.share_report(report, analyst_user.id, "<script>alert(1)</script>")
    _as(client, "intel")

    html = client.get("/workspace/threat-intel").get_data(as_text=True)

    assert "<script>alert(1)</script>" not in html and "&lt;script&gt;alert(1)&lt;/script&gt;" in html


def test_the_inbox_is_empty_until_something_is_shared(client, intel):
    _as(client, "intel")
    html = client.get("/workspace/threat-intel").get_data(as_text=True)
    assert "No reports have been shared with you yet." in html and "0 total" in html


def test_the_inbox_lists_the_newest_share_first(app, analyst_user, report, tmp_path):
    target = db.session.get(AuthorizedTarget, report.target_id)
    newer = report_service.generate_csv_report(target, str(tmp_path), analyst_user.id)
    report_share_service.share_report(report, analyst_user.id)
    report_share_service.share_report(newer, analyst_user.id)

    assert [item["report"].id for item in report_share_service.inbox()] == [newer.id, report.id]


def test_a_share_from_a_deleted_user_still_shows(app, analyst_user, report):
    share, _ = report_share_service.share_report(report, analyst_user.id)
    share.shared_by = 987654
    db.session.commit()
    assert report_share_service.inbox()[0]["shared_by"] == "a former user"


def test_the_sidebar_links_threat_intel_to_the_inbox(client, intel):
    _as(client, "intel")
    html = client.get("/workspace/threat-intel").get_data(as_text=True)
    assert 'href="/workspace/threat-intel#shared-reports">Shared Reports</a>' in html
